spring:
  application:
    name: Delivery-Tracer
  datasource:
    url: jdbc:postgresql://localhost:5433/deliveryTracer
    username: postgres
    password: postgres
    driver-name-class: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true